// This file will be auto-generated by Supabase CLI:
// npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts
//
// For now, re-export the placeholder types from lib/supabase/types.ts
// After generating, replace this file with the actual generated types.

export type { Database } from '@/lib/supabase/types'
